### ISSUE TITLE
关键词和搜索结果匹配问题

### ISSUE THREAD

**Issue by zenghuazhe** [xiaojiong/DhtCrawler#4]
老哥你好，收集了大量有效info-hash后(磁力链接)，仅仅算是一个种子收集库，如何进一步实现搜索功能？也就是将关键字和对应的一些磁力链接联系起来？

**Comment by xiaojiong** [comment]
sphinx , elasticsearch

**Comment by zenghuazhe** [comment]
多谢！

**Comment by zenghuazhe** [comment]
打扰了老哥 很急！！！对bootstrap返回的所有节点 发送find node请求都不回复。。。
节点ip和port解析应该没问题啊
help me please
